#!/bin/sh

QUEUEDIR="/var/spool/postfix-inbound/incoming/"
QUEUEDIR2="/var/spool/postfix-inbound/deferred/"
QUEUEDIR3="/var/spool/postfix-inbound/active/"

usage="Usage: "$0" -w warnlevel -c criticallevel"

while getopts  ":w::c:" options; do
	case $options in
		w ) warnlevel=$OPTARG;;
		c ) critlevel=$OPTARG;;
		h ) echo $usage;;
		\? ) echo $usage
			exit 1;;
		* ) echo $usage
			exit 1;;
	esac
done

if [ "$warnlevel" = "" ] || [ "$critlevel" = "" ]; then
	echo $usage
	exit 1
fi

queuesize=`( find $QUEUEDIR -type f ;  find $QUEUEDIR2 -type f ; find $QUEUEDIR3 -type f ) | wc -l`

echo "Inbound queue: $queuesize"

if [ "$queuesize" -ge "$critlevel" ]; then
	exit 2
elif [ "$queuesize" -ge "$warnlevel" ]; then
	exit 1
else
	exit 0
fi
