#!/bin/sh

if [ "$1" = "start" ]; then
	varnishncsa | perl -pi -e 's|^([^ ]+) ([^ ]+) ([^ ]+) ([^ ]+) ([^ ]+) ([^ ]+) https?://([^/]+)|0 $7 $1 $2 $3 $4 $5 $6 |' | /usr/bin/logger -p local6.info &
elif [ "$1" = "stop" ]; then
	killall varnishncsa
else
	echo "Usage: "$0" [start|stop]"
fi
