#!/bin/bash

logfile="/tmp/sappmng_wrapper.log"

echo "----`date`---- (start sapmng)" >> $logfile
echo "$@" >> $logfile

# Call out script - this will wait for the files to appear
# and then mod them

exec "/usr/local/psa/admin/sbin/sappmng.openhost" "$@" &

# Call the original program. This will create the directories
# and we will mod them shortly afterwards

exec "/usr/local/psa/admin/sbin/sappmng.swsoft" "$@"

