#!/usr/bin/php
<?php

date_default_timezone_set("Pacific/Auckland");

error_reporting(E_ALL|E_STRICT);
ini_set('display_errors', true);

if (!defined('APP_ROOT'))
	define('APP_ROOT', realpath(dirname(__FILE__)));

set_include_path(
	APP_ROOT . '/lib' . PATH_SEPARATOR . 
	get_include_path()
	);
	
require_once('wdmysqlbk.php');

$wdmysqlbk = new wdmysqlbk($argv);
?>
